version: '3'

services:
    app:
        container_name: slim_boilerplate
        build:
            context: .
            dockerfile: docker/app/Dockerfile
        volumes:
            - .:/var/www/html
        ports:
            - 8888:80
        env_file:
            - ./.env
        networks:
            - localnet
        depends_on:
            - mysql
    node:
        build:
            context: .
            dockerfile: docker/node/Dockerfile
        container_name: slim_boilerplate_node
        volumes:
            - ./public:/var/www/html/public
            - ./resources:/var/www/html/resources
            - ./tailwind.config.js:/var/www/html/tailwind.config.js
    mysql:
        container_name: slim_boilerplate_db
        image: mysql:5.7
        volumes:
            - dbdata:/var/lib/mysql
        ports:
            - 4306:3306
        networks:
            - localnet
        env_file:
            - ./.env
volumes:
    dbdata:
    web-root:
    node_modules:
        driver: 'local'
networks:
    localnet:
        driver: 'bridge'