version: '3'

services:
    app:
        container_name: slim_boilerplate
        build:
            context: .
            dockerfile: docker/app/Dockerfile
        volumes:
            - .:/var/www/html
        ports:
            - 8888:80
        env_file:
            - ./.env
        networks:
            - localnet

networks:
    localnet:
        driver: 'bridge'